language: node_js
node_js: "10"

cache:
  directories:
    - node_modules

before_install:
  - sudo apt-get update
  - sudo apt-get install alien # we need rpm and rpmbuild

script:
- npm audit
- npm run lint
- npm test
- npm run release

branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/" # matches branch names using semantic versioning (e.g. "v0.0.1")
